---
- name: "configure user environment"
  hosts: "vm"
  become: yes

  tasks:
    - name: "enable color in bash"
      ansible.builtin.lineinfile:
        path: "/home/a.zubkov/.bashrc"
        state: "present"
        regexp: "^#?#force_color_prompt"
        line: "force_color_prompt=yes"